const dividends = [
  {
    companyName: "ABBEY MORTGAGE BANK PLC",
    symbol: "ABBEYBDS",
    period: "FY 2024",
    dividendAmount: 0.06,
    dividendYield: 0.72,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-12",
    closureStart: "2025-05-13",
    closureEnd: "2025-05-16",
    agmDate: "2025-05-28",
    paymentDate: "2025-05-28",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africaprudential.com",
  },
  {
    companyName: "ACCESS HOLDINGS PLC",
    symbol: "ACCESSCORP",
    period: "HY 2024",
    dividendAmount: 2.05,
    dividendYield: 8.65,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-04-29",
    closureStart: "2025-04-30",
    closureEnd: "2025-04-30",
    agmDate: "2025-05-15",
    paymentDate: "2025-05-15",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://coronationregistrars.com/e-mandate/",
  },
  {
    companyName: "AIICO INSURANCE PLC",
    symbol: "AIICO",
    period: "FY 2024",
    dividendAmount: 0.07,
    dividendYield: 4.38,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-21",
    closureStart: "2025-05-22",
    closureEnd: "2025-05-26",
    agmDate: "2025-05-27",
    paymentDate: "2025-05-27",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://crhelfservice.coronation.ng/",
  },
  {
    companyName: "AIRTEL AFRICA PLC",
    symbol: "AIRTELAFRI",
    period: "H1 2025",
    dividendAmount: 40.52,
    dividendYield: 1.75,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-04",
    closureStart: "2025-11-07",
    closureEnd: "2025-11-07",
    agmDate: null,
    paymentDate: "2025-12-12",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "mailto:eforms@coronationregistrars.com",
  },
  {
    companyName: "AFRICA PRUDENTIAL PLC",
    symbol: "AFRIPRUD",
    period: "HY 2025",
    dividendAmount: 0.10,
    dividendYield: 0.65,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-08-08",
    closureStart: "2025-08-11",
    closureEnd: "2025-08-15",
    agmDate: null,
    paymentDate: "2025-08-18",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/claimyour-dividend-here/",
  },
  {
    companyName: "ARADEL HOLDINGS PLC",
    symbol: "ARADEL",
    period: "H1 2025",
    dividendAmount: 10.00,
    dividendYield: 1.41,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-20",
    closureStart: "2025-11-21",
    closureEnd: "2025-11-21",
    agmDate: null,
    paymentDate: "2025-11-28",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://coronation.ng",
  },
  {
    companyName: "AXAMANSARD INSURANCE PLC",
    symbol: "MANSARD",
    period: "FY 2024",
    dividendAmount: 0.45,
    dividendYield: 4.69,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-06-25",
    closureStart: "2025-06-26",
    closureEnd: "2025-06-26",
    agmDate: "2025-07-10",
    paymentDate: "2025-07-10",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://shorturl.at/mzU99",
  },
  {
    companyName: "BERGER PAINTS NIGERIA PLC",
    symbol: "BERGER",
    period: "H1 2025",
    dividendAmount: 0.40,
    dividendYield: 0.98,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-11",
    closureStart: "2025-11-12",
    closureEnd: "2025-11-12",
    agmDate: null,
    paymentDate: "2025-11-19",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://meristemregistrars.com",
  },
  {
    companyName: "BUA CEMENT PLC",
    symbol: "BUACEMENT",
    period: "FY 2024",
    dividendAmount: 2.50,
    dividendYield: 2.99,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-06-03",
    closureStart: "2025-07-04",
    closureEnd: "2025-07-08",
    agmDate: "2025-07-21",
    paymentDate: "2025-07-21",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://meristemregistrars.com",
  },
  {
    companyName: "BUA FOODS PLC",
    symbol: "BUAFOODS",
    period: "FY 2024",
    dividendAmount: 13.00,
    dividendYield: 3.11,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-08-21",
    closureStart: "2025-08-22",
    closureEnd: "2025-08-29",
    agmDate: "2025-09-11",
    paymentDate: "2025-09-11",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/claim-yourdividend-here/",
  },
  {
    companyName: "CAP PLC",
    symbol: "CAP",
    period: "FY 2024",
    dividendAmount: 2.40,
    dividendYield: 5.11,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-18",
    closureStart: "2025-04-21",
    closureEnd: "2025-04-25",
    agmDate: null,
    paymentDate: "2025-04-18",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://arc.vote/content/uploads/2014/04/Mix-Prudential",
  },
  {
    companyName: "CHAMPION BREW. PLC.",
    symbol: "CHAMPION",
    period: "Q4 2024",
    dividendAmount: 0.06,
    dividendYield: 1.40,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-05-09",
    closureStart: "2025-05-12",
    closureEnd: "2025-05-16",
    agmDate: "2025-05-21",
    paymentDate: "2025-05-21",
    fiscalYear: 2024,
    fiscalQuarter: 4,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/claim-yourdividend-here/",
  },
  {
    companyName: "CORNERSTONE INSURANCE PLC",
    symbol: "CORNERST",
    period: "FY 2024",
    dividendAmount: 0.27,
    dividendYield: 7.30,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-07",
    closureStart: "2025-07-08",
    closureEnd: "2025-07-12",
    agmDate: "2025-07-29",
    paymentDate: "2025-07-29",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cornerstone.com.ng",
  },
  {
    companyName: "CONOIL PLC",
    symbol: "CONOIL",
    period: "FY 2024",
    dividendAmount: 3.50,
    dividendYield: 1.84,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-11-25",
    closureStart: "2025-11-26",
    closureEnd: "2025-11-28",
    agmDate: "2025-12-19",
    paymentDate: "2025-12-23",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "http://www.meristemregistrars.com",
  },
  {
    companyName: "CONSOLIDATED HALLMARK HOLDINGS PLC",
    symbol: "CONHALLPLC",
    period: "H1 2025",
    dividendAmount: 0.10,
    dividendYield: 2.45,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-08-15",
    closureStart: "2025-08-18",
    closureEnd: "2025-08-22",
    agmDate: "2025-08-27",
    paymentDate: null,
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
  {
    companyName: "CUSTODIAN INVESTMENT PLC",
    symbol: "CUSTODIAN",
    period: "H1 2025",
    dividendAmount: 0.25,
    dividendYield: 0.89,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-08-15",
    closureStart: "2025-08-18",
    closureEnd: "2025-08-22",
    agmDate: null,
    paymentDate: "2025-09-09",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://docuhub3.nibss-plc.com.ng/edmms/self-service",
  },
  {
    companyName: "CUTIX PLC",
    symbol: "CUTIX",
    period: "FY 2025",
    dividendAmount: 0.10,
    dividendYield: 2.51,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-08-15",
    closureStart: "2025-08-18",
    closureEnd: "2025-08-22",
    agmDate: "2025-08-29",
    paymentDate: "2025-09-02",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cutipic.com.apy",
  },
  {
    companyName: "C & I LEASING PLC",
    symbol: "CILEASING",
    period: "FY 2024",
    dividendAmount: 0.10,
    dividendYield: 1.96,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-08-05",
    closureStart: "2025-08-06",
    closureEnd: "2025-08-08",
    agmDate: "2025-09-08",
    paymentDate: "2025-09-08",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cordros.com",
  },
  {
    companyName: "CWG PLC",
    symbol: "CWG",
    period: "FY 2024",
    dividendAmount: 0.39,
    dividendYield: 4.70,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-07",
    closureStart: "2025-04-09",
    closureEnd: "2025-04-09",
    agmDate: "2025-04-10",
    paymentDate: "2025-04-11",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cordros.com",
  },
  {
    companyName: "DANGOTE CEMENT PLC",
    symbol: "DANGCEM",
    period: "FY 2024",
    dividendAmount: 30.00,
    dividendYield: 6.25,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-06-09",
    closureStart: "2025-06-10",
    closureEnd: "2025-06-10",
    agmDate: "2025-06-23",
    paymentDate: "2025-06-23",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/claim-yourdividend-here/",
  },
  {
    companyName: "E-TRANZACT INTERNATIONAL PLC",
    symbol: "ETRANZACT",
    period: "FY 2024",
    dividendAmount: 0.13,
    dividendYield: 2.17,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-07",
    closureStart: "2025-07-08",
    closureEnd: "2025-07-23",
    agmDate: "2025-07-24",
    paymentDate: "2025-07-24",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://wealth.meristemng.com/",
  },
  {
    companyName: "FCMB GROUP PLC",
    symbol: "FCMB",
    period: "FY 2024",
    dividendAmount: 0.55,
    dividendYield: 6.08,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-16",
    closureStart: "2025-04-17",
    closureEnd: "2025-04-17",
    agmDate: "2025-04-29",
    paymentDate: "2025-04-29",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cardinalstoneregistrars.com",
  },
  {
    companyName: "FIRST HOLDCO PLC",
    symbol: "FIRSTHOLDCO",
    period: "FY 2024",
    dividendAmount: 0.60,
    dividendYield: 2.39,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-12",
    closureStart: "2025-05-13",
    closureEnd: "2025-05-14",
    agmDate: "2025-05-22",
    paymentDate: "2025-05-23",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: null,
  },
  {
    companyName: "FIDELITY BANK PLC",
    symbol: "FIDELITYBK",
    period: "H2 2024",
    dividendAmount: 1.25,
    dividendYield: 8.70,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-04-15",
    closureStart: "2025-04-16",
    closureEnd: "2025-04-16",
    agmDate: "2025-04-29",
    paymentDate: "2025-04-29",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: null,
  },
  {
    companyName: "FIDSON HEALTHCARE PLC",
    symbol: "FIDSON",
    period: "FY 2024",
    dividendAmount: 1.00,
    dividendYield: 5.14,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-11",
    closureStart: "2025-07-14",
    closureEnd: "2025-07-18",
    agmDate: "2025-07-04",
    paymentDate: "2025-08-01",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://shorturl.at/DhJ4",
  },
  {
    companyName: "GEREGU POWER PLC",
    symbol: "GEREGU",
    period: "FY 2025",
    dividendAmount: 9.00,
    dividendYield: 0.79,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2026-04-13",
    closureStart: "2026-04-30",
    closureEnd: "2026-04-30",
    agmDate: null,
    paymentDate: "2026-04-30",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.geregupowerplc.com",
  },
  {
    companyName: "GUARANTY TRUST HOLDING COMPANY PLC",
    symbol: "GTCO",
    period: "H1 2025",
    dividendAmount: 1.00,
    dividendYield: 1.11,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-10-07",
    closureStart: "2025-11-10",
    closureEnd: "2025-11-14",
    agmDate: null,
    paymentDate: "2025-10-15",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.datamaxregistrars.com",
  },
  {
    companyName: "HALDANE MCCALL PLC",
    symbol: "HMCALL",
    period: "FY 2024",
    dividendAmount: 0.07,
    dividendYield: 1.19,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-03-31",
    closureStart: "2025-04-01",
    closureEnd: "2025-04-04",
    agmDate: "2025-04-24",
    paymentDate: "2025-04-25",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
  {
    companyName: "IKEJA HOTEL PLC",
    symbol: "IKEJAHOTEL",
    period: "Q3 2025",
    dividendAmount: 0.03,
    dividendYield: 0.15,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-07",
    closureStart: "2025-11-10",
    closureEnd: "2025-11-14",
    agmDate: null,
    paymentDate: "2025-11-28",
    fiscalYear: 2025,
    fiscalQuarter: 3,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: null,
  },
  {
    companyName: "INFINITY TRUST MORTGAGE BANK PLC",
    symbol: "INFINITY",
    period: "FY 2024",
    dividendAmount: 0.21,
    dividendYield: 3.00,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-18",
    closureStart: "2025-04-21",
    closureEnd: "2025-04-25",
    agmDate: "2025-05-20",
    paymentDate: "2025-04-13",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africanprudential.com/downloads/",
  },
  {
    companyName: "JAIZ BANK PLC",
    symbol: "JAIZBANK",
    period: "FY 2024",
    dividendAmount: 0.07,
    dividendYield: 2.20,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-14",
    closureStart: "2025-07-15",
    closureEnd: "2025-07-15",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/forms-offers/",
  },
  {
    companyName: "JAPAUL GOLD & VENTURES PLC",
    symbol: "JAPAULGOLD",
    period: "FY 2024",
    dividendAmount: 0.04,
    dividendYield: 1.90,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-06-06",
    closureStart: "2025-06-09",
    closureEnd: "2025-06-13",
    agmDate: "2025-06-30",
    paymentDate: "2025-07-04",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.paceregistrars.com",
  },
  {
    companyName: "JULIUS BERGER NIGERIA PLC",
    symbol: "JBERGER",
    period: "FY 2024",
    dividendAmount: 3.25,
    dividendYield: 2.37,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-30",
    closureStart: "2025-06-02",
    closureEnd: "2025-06-04",
    agmDate: "2025-06-19",
    paymentDate: "2025-06-20",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africastrars.com",
  },
  {
    companyName: "LAFARGE AFRICA PLC",
    symbol: "WAPCO",
    period: "Q1 2025",
    dividendAmount: 4.00,
    dividendYield: 4.94,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-05-09",
    closureStart: "2025-05-12",
    closureEnd: "2025-05-16",
    agmDate: null,
    paymentDate: "2025-05-20",
    fiscalYear: 2025,
    fiscalQuarter: 1,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cardinalstoneregistrars.com",
  },
  {
    companyName: "LEGEND INTERNET PLC",
    symbol: "LEGENDINT",
    period: "FY 2025",
    dividendAmount: 0.06,
    dividendYield: 0.51,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-10-29",
    closureStart: "2025-10-30",
    closureEnd: "2025-10-30",
    agmDate: "2025-11-07",
    paymentDate: "2025-11-07",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.datamaxregistrars.com",
  },
  {
    companyName: "LIVINGTRUST MORTGAGE BANK PLC",
    symbol: "LIVINGTRUST",
    period: "FY 2024",
    dividendAmount: 0.08,
    dividendYield: 1.66,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-03",
    closureStart: "2025-07-04",
    closureEnd: "2025-07-08",
    agmDate: null,
    paymentDate: "2025-07-21",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/claim-your-dividend-here/",
  },
  {
    companyName: "MTN NIGERIA COMMUNICATIONS PLC",
    symbol: "MTNN",
    period: "H1 2025",
    dividendAmount: 0.03,
    dividendYield: 0.96,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-20",
    closureStart: "2025-11-21",
    closureEnd: "2025-11-21",
    agmDate: null,
    paymentDate: "2025-11-28",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://fbnqubit3.nibss-plc.com.ng/edmms/self-service",
  },
  {
    companyName: "MAY & BAKER NIGERIA PLC.",
    symbol: "MAYBAKER",
    period: "FY 2024",
    dividendAmount: 0.40,
    dividendYield: 4.49,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-20",
    closureStart: "2025-05-21",
    closureEnd: "2025-05-23",
    agmDate: "2025-06-05",
    paymentDate: "2025-06-05",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.veritasregistrars.com",
  },
  {
    companyName: "MEYER PLC",
    symbol: "MEYER",
    period: "FY 2024",
    dividendAmount: 0.30,
    dividendYield: 3.06,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-02",
    closureStart: "2025-05-05",
    closureEnd: "2025-05-09",
    agmDate: "2025-05-28",
    paymentDate: "2025-05-30",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.greenwichregistrars.com",
  },
  {
    companyName: "MECURE INDUSTRIES PLC",
    symbol: "MECURE",
    period: "FY 2024",
    dividendAmount: 0.15,
    dividendYield: 1.20,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-18",
    closureStart: "2025-04-21",
    closureEnd: "2025-04-25",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cordros.com",
  },
  {
    companyName: "MULTIVERSE MINING AND EXPLORATION PLC",
    symbol: "MULTIVERSE",
    period: "FY 2024",
    dividendAmount: 0.10,
    dividendYield: 1.28,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-23",
    closureStart: "2025-05-26",
    closureEnd: "2025-05-30",
    agmDate: "2025-06-11",
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "mailto:info@carmanionregistrars.com",
  },
  {
    companyName: "MUTUAL BENEFITS ASSURANCE PLC",
    symbol: "MBENEFIT",
    period: "FY 2024",
    dividendAmount: 0.02,
    dividendYield: 1.39,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-24",
    closureStart: "2025-07-25",
    closureEnd: "2025-07-25",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: null,
  },
  {
    companyName: "NIGERIAN AVIATION HANDLING COMPANY PLC",
    symbol: "NAHCO",
    period: "FY 2025",
    dividendAmount: 5.95,
    dividendYield: 8.35,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-09",
    closureStart: "2025-05-12",
    closureEnd: "2025-05-14",
    agmDate: "2025-05-23",
    paymentDate: "2025-05-23",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cardinalstoneregistrars.com",
  },
  {
    companyName: "NASCON ALLIED INDUSTRIES PLC",
    symbol: "NASCON",
    period: "FY 2024",
    dividendAmount: 0.02,
    dividendYield: 4.78,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-16",
    closureStart: "2025-04-17",
    closureEnd: "2025-04-17",
    agmDate: "2025-05-08",
    paymentDate: "2025-05-09",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://registrars.meristemng.com",
  },
  {
    companyName: "NEM INSURANCE PLC",
    symbol: "NEM",
    period: "FY 2024",
    dividendAmount: 1.00,
    dividendYield: 7.41,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-25",
    closureStart: "2025-04-28",
    closureEnd: "2025-04-30",
    agmDate: "2025-05-20",
    paymentDate: "2025-05-20",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.apel.com.ng",
  },
  {
    companyName: "NIGERIA INFRASTRUCTURE DEBT FUND",
    symbol: "NIDF",
    period: "Q4 2025",
    dividendAmount: 5.00,
    dividendYield: 3.54,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2026-01-30",
    closureStart: "2026-01-31",
    closureEnd: "2026-01-31",
    agmDate: null,
    paymentDate: "2026-02-06",
    fiscalYear: 2025,
    fiscalQuarter: 4,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://coronationregistrars.com/e-mandate/",
  },
  {
    companyName: "N NIG. FLOUR MILLS PLC",
    symbol: "NNFM",
    period: "FY 2025",
    dividendAmount: 0.25,
    dividendYield: 0.18,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-09-17",
    closureStart: "2025-09-18",
    closureEnd: "2025-09-25",
    agmDate: "2025-09-25",
    paymentDate: "2025-09-26",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.atlasregistrars.com",
  },
  {
    companyName: "NIGERIAN EXCHANGE GROUP",
    symbol: "NXGGROUP",
    period: "H1 2025",
    dividendAmount: 1.00,
    dividendYield: 1.77,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-07",
    closureStart: "2025-11-10",
    closureEnd: "2025-11-14",
    agmDate: null,
    paymentDate: "2025-11-18",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cognilloforms.com/DataMaxGroup1/emandateform",
  },
  {
    companyName: "OKOMU OIL PALM COMPANY PLC",
    symbol: "OKOMUOIL",
    period: "Q2 2025",
    dividendAmount: 10.00,
    dividendYield: 0.98,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-10-31",
    closureStart: "2025-11-03",
    closureEnd: "2025-11-07",
    agmDate: null,
    paymentDate: "2025-11-14",
    fiscalYear: 2025,
    fiscalQuarter: 2,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.cardialstoneregistrars.com",
  },
  {
    companyName: "PRESCO PLC",
    symbol: "PRESCO",
    period: "H1 2025",
    dividendAmount: 30.00,
    dividendYield: 2.03,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-07",
    closureStart: "2025-11-10",
    closureEnd: "2025-11-14",
    agmDate: null,
    paymentDate: "2025-11-28",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://docuhub3.nibss-plc.com.ng/edmms/self-service",
  },
  {
    companyName: "SEPLAT ENERGY PLC",
    symbol: "SEPLAT",
    period: "Q3 2025",
    dividendAmount: 108.23,
    dividendYield: null,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-11-13",
    closureStart: "2025-11-14",
    closureEnd: "2025-11-14",
    agmDate: null,
    paymentDate: "2025-11-28",
    fiscalYear: 2025,
    fiscalQuarter: 3,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.datamaxregistrars.com",
  },
  {
    companyName: "SKYWAY AVIATION HANDLING COMPANY PLC",
    symbol: "SKYAVN",
    period: "FY 2024",
    dividendAmount: 0.60,
    dividendYield: 0.90,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-30",
    closureStart: "2025-06-02",
    closureEnd: "2025-06-26",
    agmDate: "2025-06-26",
    paymentDate: "2025-06-26",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.registrars.apel.com.ng",
  },
  {
    companyName: "SFS REAL ESTATE INVESTMENT TRUST",
    symbol: "SFSREIT",
    period: "FY 2024",
    dividendAmount: 21.50,
    dividendYield: 10.44,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-25",
    closureStart: "2025-04-28",
    closureEnd: "2025-05-02",
    agmDate: null,
    paymentDate: "2025-05-19",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.paceregistrars.com",
  },
  {
    companyName: "SOVEREIGN TRUST INSURANCE PLC",
    symbol: "SOVRENINS",
    period: "FY 2024",
    dividendAmount: 0.05,
    dividendYield: 5.00,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-09-05",
    closureStart: "2025-09-08",
    closureEnd: "2025-09-08",
    agmDate: "2025-09-25",
    paymentDate: "2025-09-25",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://docuhub3.nibss-plc.com.ng/edmms/self-service",
  },
  {
    companyName: "STERLING FINANCIAL HOLDINGS COMPANY PLC",
    symbol: "STERLINGNG",
    period: "FY 2024",
    dividendAmount: 0.18,
    dividendYield: null,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-07-01",
    closureStart: "2025-07-02",
    closureEnd: "2025-07-04",
    agmDate: "2025-07-11",
    paymentDate: "2025-07-11",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.aaceregistrars.com",
  },
  {
    companyName: "STANBIC IBTC HOLDINGS PLC",
    symbol: "STANBIC",
    period: "H1 2025",
    dividendAmount: 2.50,
    dividendYield: 2.55,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-10-06",
    closureStart: "2025-10-07",
    closureEnd: "2025-10-14",
    agmDate: null,
    paymentDate: "2025-10-21",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.firstregistrarsnigeria.com/downloadforms/",
  },
  {
    companyName: "SUNU ASSURANCES NIGERIA PLC",
    symbol: "SUNUASSUR",
    period: "FY 2024",
    dividendAmount: 0.10,
    dividendYield: 1.93,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-30",
    closureStart: "2025-06-02",
    closureEnd: "2025-06-06",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.crescentregistrars.com/content/downloads/e-dividend",
  },
  {
    companyName: "THE INITIATES PLC",
    symbol: "TIP",
    period: "FY 2024",
    dividendAmount: 0.10,
    dividendYield: 2.38,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-04",
    closureStart: "2025-04-07",
    closureEnd: "2025-04-10",
    agmDate: "2025-04-25",
    paymentDate: "2025-04-28",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.apel.com.ng",
  },
  {
    companyName: "TOTAL ENERGIES MARKETING NIGERIA PLC",
    symbol: "TOTAL",
    period: "FY 2024",
    dividendAmount: 40.00,
    dividendYield: 5.88,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-22",
    closureStart: "2025-04-23",
    closureEnd: "2025-04-25",
    agmDate: "2025-05-16",
    paymentDate: "2025-05-16",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://shorturl.at/r3978",
  },
  {
    companyName: "TRANSCORP HOTELS",
    symbol: "TRANSCOHOT",
    period: "Q4 2024",
    dividendAmount: 0.64,
    dividendYield: 0.51,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-03-25",
    closureStart: "2025-03-26",
    closureEnd: "2025-04-03",
    agmDate: "2025-05-16",
    paymentDate: "2025-05-16",
    fiscalYear: 2024,
    fiscalQuarter: 4,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africaprudential.com",
  },
  {
    companyName: "TRANSNATIONAL POWER PLC",
    symbol: "TRANSPOWER",
    period: "FY 2024",
    dividendAmount: 4.00,
    dividendYield: 1.30,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2026-03-17",
    closureStart: "2026-04-20",
    closureEnd: "2026-04-24",
    agmDate: "2026-05-04",
    paymentDate: "2025-05-05",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africaprudential.com/unclaimed-dividend/",
  },
  {
    companyName: "TRANSNATIONAL CORPORATION PLC",
    symbol: "TRANSCORP",
    period: "FY 2024",
    dividendAmount: 0.60,
    dividendYield: 1.28,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-03-27",
    closureStart: "2025-03-28",
    closureEnd: "2025-04-03",
    agmDate: "2025-04-09",
    paymentDate: "2025-04-16",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africaprudential.com",
  },
  {
    companyName: "UAC OF NIGERIA PLC.",
    symbol: "UACN",
    period: "FY 2024",
    dividendAmount: 0.22,
    dividendYield: 0.62,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-21",
    closureStart: "2025-05-22",
    closureEnd: "2025-05-28",
    agmDate: "2025-06-04",
    paymentDate: "2025-06-05",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.africaprudential.com",
  },
  {
    companyName: "UNITED BANK FOR AFRICA PLC",
    symbol: "UBA",
    period: "H1 2025",
    dividendAmount: 0.25,
    dividendYield: 0.53,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-10-03",
    closureStart: "2025-10-06",
    closureEnd: "2025-10-06",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/unclaimed-dividend/",
  },
  {
    companyName: "UNITED CAPITAL PLC",
    symbol: "UCAP",
    period: "Q4 2024",
    dividendAmount: 0.50,
    dividendYield: 2.60,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-03-14",
    closureStart: "2025-03-17",
    closureEnd: "2025-03-21",
    agmDate: "2025-04-04",
    paymentDate: "2025-04-04",
    fiscalYear: 2024,
    fiscalQuarter: 4,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://africaprudential.com/",
  },
  {
    companyName: "UNIVERSITY PRESS PLC",
    symbol: "UPL",
    period: "FY 2025",
    dividendAmount: 1.15,
    dividendYield: 2.68,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-08-22",
    closureStart: "2025-08-25",
    closureEnd: "2025-08-28",
    agmDate: "2025-09-18",
    paymentDate: "2025-08-22",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.greenwichregistrars.com",
  },
  {
    companyName: "UNILEVER NIGERIA PLC",
    symbol: "UNILEVER",
    period: "H1 2025",
    dividendAmount: 0.05,
    dividendYield: 0.73,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-08-08",
    closureStart: "2025-08-11",
    closureEnd: "2025-08-15",
    agmDate: null,
    paymentDate: "2025-08-22",
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.greenwichregistrars.com",
  },
  {
    companyName: "UPDC PLC",
    symbol: "UPDC",
    period: "FY 2024",
    dividendAmount: 0.01,
    dividendYield: 0.36,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-04-30",
    closureStart: "2025-05-01",
    closureEnd: "2025-05-06",
    agmDate: "2025-05-14",
    paymentDate: "2025-05-14",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.greenwichregistrars.com",
  },
  {
    companyName: "VFD GROUP PLC",
    symbol: "VFDGROUP",
    period: "FY 2024",
    dividendAmount: 2.50,
    dividendYield: 4.30,
    dividendType: "final",
    bonusShares: "5 for 1",
    qualificationDate: "2025-04-02",
    closureStart: "2025-04-23",
    closureEnd: "2025-04-24",
    agmDate: "2025-05-08",
    paymentDate: "2025-05-08",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
  {
    companyName: "VITAFOAM NIGERIA PLC",
    symbol: "VITAFOAM",
    period: "FY 2024",
    dividendAmount: 3.00,
    dividendYield: 3.26,
    dividendType: "final",
    bonusShares: "1 for 5",
    qualificationDate: "2026-02-06",
    closureStart: "2026-02-09",
    closureEnd: "2026-02-13",
    agmDate: "2026-03-05",
    paymentDate: "2026-03-05",
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
  {
    companyName: "WEMA BANK PLC",
    symbol: "WEMA",
    period: "FY 2024",
    dividendAmount: 1.00,
    dividendYield: 8.16,
    dividendType: "final",
    bonusShares: null,
    qualificationDate: "2025-05-01",
    closureStart: "2025-05-02",
    closureEnd: "2025-05-07",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2024,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
  {
    companyName: "ZENITH BANK PLC",
    symbol: "ZENITHBANK",
    period: "H1 2025",
    dividendAmount: 1.25,
    dividendYield: 1.89,
    dividendType: "interim",
    bonusShares: null,
    qualificationDate: "2025-10-03",
    closureStart: "2025-10-06",
    closureEnd: "2025-10-06",
    agmDate: null,
    paymentDate: null,
    fiscalYear: 2025,
    currency: "NGN",
    source: "Corporate Action Calendar",
    eDividendRegistrationUrl: "https://www.meristemregistrars.com",
  },
];

async function seedDividends() {
  console.log(`Seeding ${dividends.length} dividend records...`);
  const apiKey = process.env.API_SECRET_KEY;
  if (!apiKey) {
    console.error('Error: API_SECRET_KEY environment variable is required');
    process.exit(1);
  }
  const response = await fetch('http://localhost:5000/api/dividends/bulk', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
    },
    body: JSON.stringify({ dividends }),
  });
  const result = await response.json();
  console.log('Seed result:', result);
}

seedDividends();
